DROP DATABASE IF EXISTS businessDB;
CREATE DATABASE businessDB;

USE businessDB;

CREATE TABLE department (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE role (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(30) UNIQUE NOT NULL,
  SALARY DECIMAL NOT NULL,
  DEPT_ID INT NOT NULL,
);

CREATE TABLE employees (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(30) NOT NULL,
  LAST_NAME VARCHAR(30) NOT NULL,
  ROLE_ID INT NOT NULL,
  MANAGER_ID INT,
);